### ISSUE TITLE
It throws NullPointerException sometimes over usages of 'mViewRef'

### ISSUE THREAD

**Issue by himanshubb** [trafi/anchor-bottom-sheet-behavior#21]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference`

I am getting this issue in some of the devices.
I would like to suggest that `mViewRef` should be declared as `@Nullable`.
and `Null` checks should be added to the remaining places where it was being used within the [AnchorBottomSheetBehavior.java](https://raw.githubusercontent.com/trafi/anchor-bottom-sheet-behavior/master/library/src/main/java/com/trafi/anchorbottomsheetbehavior/AnchorBottomSheetBehavior.java)

**Comment by justasm** [comment]
Hi, I'd recommend migrating to use [Google's Material bottom sheet](https://material.io/components/sheets-bottom/android#using-standard-bottom-sheets), which recently supports [`STATE_HALF_EXPANDED`](https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior#STATE_HALF_EXPANDED).

Otherwise, contributions are welcome.

**Comment by himanshubb** [comment]
Okay thanks @justasm 
I will plan for it.
